# $(VIM_FILEPATH)    # File name of current buffer with full path.
# $(VIM_FILENAME)    # File name of current buffer without path.
# $(VIM_FILEDIR)     # Full path of current buffer without the file name.
# $(VIM_FILEEXT)     # File extension of current buffer.
# $(VIM_FILETYPE)    # File type (value of &ft in vim)
# $(VIM_FILENOEXT)   # File name of current buffer without path and extension.
# $(VIM_PATHNOEXT)   # Current file name with full path but without extension.
# $(VIM_CWD)         # Current directory (which :pwd returns).
# $(VIM_RELDIR)      # File path relativize to current directory.
# $(VIM_RELNAME)     # File name relativize to current directory.
# $(VIM_ROOT)        # Project root directory.
# $(VIM_CWORD)       # Word under cursor.
# $(VIM_CFILE)       # File name under cursor.
# $(VIM_CLINE)       # Cursor line number in current buffer
# $(VIM_GUI)         # has('gui_runnin')?

# [+]
# C_FLAGS=-Wall -std=c++17 -O2
# CXX_FLAGS=-Wall -std=c++17 -O2

[file-build:release]
cmd:c=gcc   -Wall -std=c++17 -O2 $(VIM_FILEPATH) -o $(VIM_FILEDIR)/build/$(VIM_ARCH)/release/$(VIM_FILENOEXT)
cmd:cpp=g++ -Wall -std=c++17 -O2 $(VIM_FILEPATH) -o $(VIM_FILEDIR)/build/$(VIM_ARCH)/release/$(VIM_FILENOEXT)
out_dir=$(VIM_FILEDIR)/build/$(VIM_ARCH)/release/
output=quickfix
save=1

[file-build:debug]
cmd:c=gcc   -Wall -std=c++17 -g $(VIM_FILEPATH) -o $(VIM_FILEDIR)/build/$(VIM_ARCH)/debug/$(VIM_FILENOEXT)
cmd:cpp=g++ -Wall -std=c++17 -g $(VIM_FILEPATH) -o $(VIM_FILEDIR)/build/$(VIM_ARCH)/debug/$(VIM_FILENOEXT)
out_dir=$(VIM_FILEDIR)/build/$(VIM_ARCH)/debug/
output=quickfix
save=1

[file-run:release]
cmd=$(VIM_FILEDIR)/build/$(VIM_ARCH)/release/$(VIM_FILENOEXT)
cwd=$(VIM_CWD)
output=terminal
save=1

[file-run:debug]
cmd=$(VIM_FILEDIR)/build/$(VIM_ARCH)/debug/$(VIM_FILENOEXT)
cwd=$(VIM_CWD)
output=terminal
save=1

[file-run]
cmd:python=python -u $(VIM_FILENAME)
cmd:sh=bash $(VIM_FILENAME)
cmd:zsh=zsh $(VIM_FILENAME)
cmd:dockerfile=docker build .
cmd:lua=luajit $(VIM_FILENAME)
output=terminal
save=1

[project-build]
cmd=make build
output=quickfix
save=2

[project-run]
cmd=make run
output=terminal
save=2
